import type { FastifyInstance } from "fastify";
import type { StorySourceAdapter } from "../adapters/types.js";
import type { NeteaseAuthService } from "../adapters/music/netease-auth.js";
import type { MemoryRepository } from "../state/memory-repository.js";
import type { StateRepository } from "../state/state-repository.js";
import type { UserPreferences } from "../user/load-user-preference.js";
import type { FavoritesRepository } from "../user/favorites-repository.js";
import type { LikedSongsRepository } from "../user/liked-songs-repository.js";
import type { SessionRepository } from "../user/session-repository.js";
import type { TrackRegistry } from "../audio/track-registry.js";
import type { PlaybackState } from "./playback-state.js";
import type { LlmAdapter, MusicAdapter, TtsAdapter, WeatherAdapter, CalendarAdapter, DeviceAdapter } from "../adapters/types.js";
import type { StreamBroadcaster } from "../realtime/stream-bus.js";
import type { ProgramBriefRepository } from "../show/program-brief-repository.js";
import type { ShowPlanRepository } from "../show/show-plan-repository.js";
import type { ShowPlanGenerator } from "../show/show-plan-generator.js";
import type { DailyShowPlanGenerator } from "../show/daily-show-plan-generator.js";
import type { JobRegistry } from "../show/show-generation-job.js";
import type { ShowProjectRepository } from "../show/show-project-repository.js";

export type RegisterRoutesDeps = {
  app: FastifyInstance;
  state: PlaybackState;
  stateRepo: StateRepository;
  stream: StreamBroadcaster;
  memory: MemoryRepository;
  favorites: FavoritesRepository;
  likedSongs: LikedSongsRepository;
  sessionRepo: SessionRepository;
  trackRegistry: TrackRegistry;
  audioDir: string;
  exportDir: string;
  llm: LlmAdapter;
  llmStatus: string;
  music: MusicAdapter;
  musicStatus: string;
  ttsStatus: string;
  tts: TtsAdapter;
  ttsCacheDir: string;
  systemPrompt: string;
  userPreferences: UserPreferences;
  weather: WeatherAdapter;
  calendar: CalendarAdapter;
  devices: DeviceAdapter;
  storySource: StorySourceAdapter;
  publicMetadataAdapter?: StorySourceAdapter | undefined;
  webResearchAdapter?: StorySourceAdapter | undefined;
  currentMoodHint: string;
  nowProvider: () => Date;
  storySourceStatus: string;
  webResearchStatus: string;
  neteaseAuth: NeteaseAuthService;
  baseDir: string;
  programBriefRepo: ProgramBriefRepository;
  showPlanRepo: ShowPlanRepository;
  showPlanGenerator: ShowPlanGenerator;
  dailyShowPlanGenerator: DailyShowPlanGenerator;
  jobRegistry: JobRegistry;
  showProjectRepo: ShowProjectRepository;
};
